#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Terraform version
#
# Usage: KZENV exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Terraform
# version's `bin' directory is at the front.
#
# For example, if the currently selected Terraform version is 0.7.0:
#   KZENV exec build
#
# is equivalent to:
#   PATH="$KZENV_ROOT/versions/0.7.0/bin:$PATH" kustomize build

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${KZENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine KZENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine KZENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  KZENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n ${KZENV_ROOT} ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine KZENV_ROOT";
else
  KZENV_ROOT="${KZENV_ROOT%/}";
fi;
export KZENV_ROOT;

if [ -n "${KZENV_HELPERS:-""}" ]; then
  log 'debug' 'KZENV_HELPERS is set, not sourcing helpers again';
else
  [ "${KZENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${KZENV_ROOT}/lib/helpers.sh";
  if source "${KZENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${KZENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${KZENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${KZENV_ROOT}/${dir}', not adding it again";;
    *) 
      log 'debug' "\$PATH does not contain '${KZENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${KZENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

log 'debug' 'Getting version from kzenv-version-name';
KZENV_VERSION="$(kzenv-version-name)" \
  && log 'debug' "KZENV_VERSION is ${KZENV_VERSION}" \
  || {
    # Errors will be logged from KZENV-version name,
    # we don't need to trouble STDERR with repeat information here
    log 'debug' 'Failed to get version from kzenv-version-name';
    exit 1;
  };
export KZENV_VERSION;

KUSTOMIZE_BIN_PATH="${KZENV_ROOT}/versions/${KZENV_VERSION}/kustomize";
export PATH="${KUSTOMIZE_BIN_PATH}:${PATH}";
log 'debug' "KUSTOMIZE_BIN_PATH added to PATH: ${KUSTOMIZE_BIN_PATH}";
log 'debug' "Executing: ${KUSTOMIZE_BIN_PATH} ${@}";

exec "${KUSTOMIZE_BIN_PATH}" "${@}" \
  || log 'error' "Failed to execute: ${KUSTOMIZE_BIN_PATH} ${@}";

exit 0;
